import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { formatGithub, formatJson, formatText } from './format.js';
import { runCheck } from './index.js';
import { classifyLines } from './regions.js';
import { runSyntaxRules } from './rules/syntax.js';
import { collectSidebarIds, docIdFor, loadSidebars } from './structure.js';
import type { FileContext, Finding } from './types.js';

function scan(markdown: string, futureV4 = false): Finding[] {
  const lines = markdown.split('\n');
  const { regions, findings } = classifyLines('docs/test.md', lines);
  return [
    ...findings,
    ...runSyntaxRules({
      file: 'docs/test.md',
      lines,
      regions,
      futureV4,
    } satisfies FileContext),
  ];
}

describe('S2.1.1 — admonitions', () => {
  it('flags a space-separated title with the exact fix', () => {
    const findings = scan(':::warning Be careful\ncontent\n:::');
    expect(findings).toHaveLength(1);
    expect(findings[0]).toMatchObject({
      rule: 'admonition-space-title',
      line: 1,
      severity: 'error',
      suggestion: 'use :::warning[Be careful]',
    });
  });

  it('is silent on the correct bracket form and bare admonitions', () => {
    expect(scan(':::warning[Be careful]\ncontent\n:::')).toHaveLength(0);
    expect(scan(':::tip\ncontent\n:::')).toHaveLength(0);
  });

  it('flags an unclosed admonition at its opening line', () => {
    const findings = scan('# Doc\n\n:::note\nnever closed');
    expect(findings).toMatchObject([{ rule: 'unclosed-admonition', line: 3 }]);
  });

  it('handles nested admonitions with more colons', () => {
    expect(scan('::::info[Outer]\n:::note\ninner\n:::\n::::')).toHaveLength(0);
  });

  it('ignores admonition syntax inside code fences', () => {
    expect(scan('```md\n:::warning Title\n```')).toHaveLength(0);
  });
});

describe('S2.1.1 — fences', () => {
  it('flags an unclosed fence at its opening line', () => {
    const findings = scan('# Doc\n\n```ts\nconst x = 1;');
    expect(findings).toMatchObject([{ rule: 'unclosed-fence', line: 3 }]);
  });

  it('is silent on closed fences and longer closing markers', () => {
    expect(scan('```ts\ncode\n```')).toHaveLength(0);
    expect(scan('````md\n```ts\ninner\n```\n````')).toHaveLength(0);
  });
});

describe('S2.1.1 — MDX hazards', () => {
  it('flags < followed by a digit in prose', () => {
    const findings = scan('Latency is <10ms on average.');
    expect(findings).toMatchObject([
      { rule: 'mdx-lt-digit', line: 1, severity: 'error' },
    ]);
  });

  it('is silent for <digit in fences and inline code', () => {
    expect(scan('```\nif (x <3) {}\n```')).toHaveLength(0);
    expect(scan('Latency is `<10ms` on average.')).toHaveLength(0);
  });

  it('flags {#custom-id} headings only under future.v4', () => {
    const doc = '## Direction audit {#direction-audit}';
    expect(scan(doc, true)).toMatchObject([
      { rule: 'heading-custom-id-v4', line: 1 },
    ]);
    expect(scan(doc, false)).toHaveLength(0);
  });
});

describe('S2.1.1 — mermaid labels', () => {
  it('flags unquoted parens in node text with the quoted fix', () => {
    const findings = scan(
      '```mermaid\ngraph TD\n  A[Server (main)] --> B\n```',
    );
    expect(findings).toMatchObject([
      { rule: 'mermaid-unquoted-parens', line: 3, severity: 'warning' },
    ]);
    expect(findings[0].suggestion).toContain('["Server (main)"]');
  });

  it('is silent for quoted labels and parens outside mermaid', () => {
    expect(
      scan('```mermaid\ngraph TD\n  A["Server (main)"] --> B\n```'),
    ).toHaveLength(0);
    expect(scan('Text with (parens) [and brackets].')).toHaveLength(0);
  });
});

describe('S2.1.2 — structure', () => {
  it('derives doc ids with number-prefix stripping and frontmatter override', () => {
    expect(docIdFor('guides/01-intro.md')).toBe('guides/intro');
    expect(docIdFor('guides/setup.mdx', 'custom-id')).toBe('guides/custom-id');
  });

  it('collects explicit ids and detects autogenerated slices', () => {
    const scan1 = collectSidebarIds({
      docsSidebar: [
        'intro',
        { type: 'doc', id: 'guides/setup' },
        {
          type: 'category',
          label: 'Deep',
          link: { type: 'doc', id: 'deep/index' },
          items: ['deep/one'],
        },
      ],
    });
    expect([...scan1.referenced].sort()).toEqual([
      'deep/index',
      'deep/one',
      'guides/setup',
      'intro',
    ]);
    expect(scan1.hasAutogenerated).toBe(false);
    expect(
      collectSidebarIds({ s: [{ type: 'autogenerated', dirName: '.' }] })
        .hasAutogenerated,
    ).toBe(true);
  });
});

describe('runCheck end to end', () => {
  const tempDirs: string[] = [];
  afterEach(async () => {
    await Promise.all(
      tempDirs.splice(0).map((d) => rm(d, { recursive: true, force: true })),
    );
  });

  async function site(files: Record<string, string>): Promise<string> {
    const dir = await mkdtemp(path.join(os.tmpdir(), 'pokedocs-check-'));
    tempDirs.push(dir);
    for (const [rel, content] of Object.entries(files)) {
      await mkdir(path.dirname(path.join(dir, rel)), { recursive: true });
      await writeFile(path.join(dir, rel), content);
    }
    return dir;
  }

  it('reports syntax + structural findings across a site, sorted', async () => {
    const dir = await site({
      'docusaurus.config.ts': 'export default { future: { v4: true } };',
      'sidebars.ts': `import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = { docs: ['intro', 'missing-page'] };
export default sidebars;`,
      'docs/intro.md': '# Intro\n\n:::warning Watch out\ntext\n:::\n',
      'docs/orphan.md': '# Orphan\n\nfine content\n',
      'docs/hidden.md': '---\nunlisted: true\n---\n\n# Hidden\n',
    });
    const summary = await runCheck(dir);
    expect(summary.filesChecked).toBe(3);
    const rules = summary.findings.map((f) => f.rule);
    expect(rules).toContain('admonition-space-title');
    expect(rules).toContain('dangling-sidebar-entry');
    expect(rules).toContain('orphaned-page');
    expect(rules).not.toContain('heading-custom-id-v4');
    // hidden.md is unlisted → not an orphan finding
    expect(
      summary.findings.filter((f) => f.rule === 'orphaned-page'),
    ).toMatchObject([{ file: 'docs/orphan.md' }]);
  });

  it('is silent on a clean site with an autogenerated sidebar', async () => {
    const dir = await site({
      'sidebars.ts':
        "export default { docs: [{ type: 'autogenerated', dirName: '.' }] };",
      'docs/intro.md':
        '# Intro\n\n:::tip[Nice]\ngood\n:::\n\n```mermaid\ngraph TD\n  A["ok (fine)"] --> B\n```\n',
    });
    const summary = await runCheck(dir);
    expect(summary.findings).toHaveLength(0);
  });

  it('evaluates a typescript sidebars file', async () => {
    const dir = await site({
      'sidebars.ts': `import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};
export default sidebars;`,
    });
    const sidebars = await loadSidebars(dir);
    expect(collectSidebarIds(sidebars).hasAutogenerated).toBe(true);
  });
});

describe('S2.1.3 — output formats', () => {
  const summary = {
    findings: [
      {
        file: 'docs/a.md',
        line: 3,
        rule: 'mdx-lt-digit',
        severity: 'error' as const,
        message: 'bad',
        suggestion: 'escape it',
      },
    ],
    filesChecked: 2,
    errors: 1,
    warnings: 0,
  };

  it('renders text with file, line, and fix', () => {
    const text = formatText(summary);
    expect(text).toContain('docs/a.md');
    expect(text).toContain('mdx-lt-digit:3');
    expect(text).toContain('fix: escape it');
    expect(text).toContain('1 errors, 0 warnings in 2 files');
  });

  it('renders parseable json', () => {
    expect(JSON.parse(formatJson(summary)).errors).toBe(1);
  });

  it('renders github annotations', () => {
    expect(formatGithub(summary)).toBe(
      '::error file=docs/a.md,line=3,title=mdx-lt-digit::bad. Fix: escape it',
    );
  });
});
