/**
 * Structural checks (S2.1.2): pages unreachable from any sidebar, and
 * sidebar entries pointing at docs that don't exist. Sidebars are
 * evaluated from the site's sidebars.ts/js with a light TS-strip — if
 * that fails, structural checks skip gracefully rather than lie.
 */

import { readFile } from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
import type { Finding } from './types.js';

export interface DocInfo {
  /** Path relative to the site dir, e.g. "docs/guides/intro.md". */
  file: string;
  /** Docusaurus doc id, e.g. "guides/intro". */
  id: string;
  draft: boolean;
  unlisted: boolean;
}

/** Docusaurus strips list-ordering prefixes like "01-" from ids. */
function stripNumberPrefix(segment: string): string {
  return segment.replace(/^\d+[-_. ]/, '');
}

export function docIdFor(relToDocsDir: string, frontmatterId?: string): string {
  const noExt = relToDocsDir.replace(/\.mdx?$/, '');
  const segments = noExt.split('/').map(stripNumberPrefix);
  if (frontmatterId) {
    segments[segments.length - 1] = frontmatterId;
  }
  return segments.join('/');
}

/** Minimal frontmatter scalar reader — enough for id/draft/unlisted. */
export function readFrontmatterScalars(
  lines: string[],
): Record<string, string> {
  if (lines[0]?.trim() !== '---') {
    return {};
  }
  const values: Record<string, string> = {};
  for (let i = 1; i < lines.length; i += 1) {
    if (lines[i].trim() === '---') {
      break;
    }
    const match = lines[i].match(/^([\w-]+):\s*(.*)$/);
    if (match) {
      values[match[1]] = match[2].trim().replace(/^["']|["']$/g, '');
    }
  }
  return values;
}

export interface SidebarScan {
  /** Doc ids referenced explicitly anywhere in any sidebar. */
  referenced: Set<string>;
  /** True if any sidebar uses an autogenerated slice (all docs reachable). */
  hasAutogenerated: boolean;
}

export function collectSidebarIds(sidebars: unknown): SidebarScan {
  const referenced = new Set<string>();
  let hasAutogenerated = false;

  const visit = (node: unknown): void => {
    if (typeof node === 'string') {
      referenced.add(node);
      return;
    }
    if (Array.isArray(node)) {
      for (const item of node) {
        visit(item);
      }
      return;
    }
    if (typeof node !== 'object' || node === null) {
      return;
    }
    const entry = node as Record<string, unknown>;
    if (entry.type === 'autogenerated') {
      hasAutogenerated = true;
      return;
    }
    if (
      (entry.type === 'doc' || entry.type === 'ref') &&
      typeof entry.id === 'string'
    ) {
      referenced.add(entry.id);
    }
    if (typeof entry.link === 'object' && entry.link !== null) {
      const link = entry.link as Record<string, unknown>;
      if (link.type === 'doc' && typeof link.id === 'string') {
        referenced.add(link.id);
      }
    }
    if (Array.isArray(entry.items)) {
      visit(entry.items);
    }
    // Top-level sidebars object: { sidebarName: [...] }
    if (entry.type === undefined && entry.items === undefined) {
      for (const value of Object.values(entry)) {
        visit(value);
      }
    }
  };

  visit(sidebars);
  return { referenced, hasAutogenerated };
}

/**
 * Evaluate sidebars.(ts|js) without a TypeScript toolchain: strip the
 * type-only surface (imports, annotations, satisfies) and run the rest
 * in a sandbox. Returns null when the file is too clever for that —
 * callers must then skip structural checks, loudly.
 */
export async function loadSidebars(siteDir: string): Promise<unknown | null> {
  let source: string | null = null;
  for (const name of ['sidebars.ts', 'sidebars.js', 'sidebars.mjs']) {
    source = await readFile(path.join(siteDir, name), 'utf8').catch(() => null);
    if (source !== null) {
      break;
    }
  }
  if (source === null) {
    return null;
  }

  const stripped = source
    .replace(/^import\s[^;]*;\s*$/gm, '')
    .replace(/^export\s+default\s+/m, 'module.exports = ')
    .replace(
      /module\.exports\s*=\s*sidebars\s*;?\s*$/m,
      'module.exports = sidebars;',
    )
    .replace(/:\s*SidebarsConfig\b/g, '')
    .replace(/\ssatisfies\s+[\w.]+/g, '');

  try {
    const sandbox: { module: { exports: unknown } } = {
      module: { exports: {} },
    };
    vm.runInNewContext(stripped, sandbox, { timeout: 1000 });
    return sandbox.module.exports;
  } catch {
    return null;
  }
}

export function structuralFindings(
  docs: DocInfo[],
  scan: SidebarScan | null,
  sidebarsFile: string,
): Finding[] {
  if (scan === null) {
    return [];
  }
  const findings: Finding[] = [];
  const docIds = new Set(docs.map((d) => d.id));

  for (const id of scan.referenced) {
    if (!docIds.has(id)) {
      findings.push({
        file: sidebarsFile,
        line: 0,
        rule: 'dangling-sidebar-entry',
        severity: 'error',
        message: `sidebar references doc id "${id}" but no such doc exists`,
        suggestion:
          'fix the id or remove the entry — this is a broken nav link',
      });
    }
  }

  if (!scan.hasAutogenerated) {
    for (const doc of docs) {
      if (doc.draft || doc.unlisted || scan.referenced.has(doc.id)) {
        continue;
      }
      findings.push({
        file: doc.file,
        line: 0,
        rule: 'orphaned-page',
        severity: 'warning',
        message: `page is not reachable from any sidebar`,
        suggestion:
          'add it to a sidebar, or mark it unlisted: true / draft: true if intentional',
      });
    }
  }

  return findings;
}
