/**
 * create-pokedocs — the scaffolder (PRD F1.1).
 *
 * `npx create-pokedocs my-docs` generates a docs-only site: docs at the root
 * path, autogenerated sidebar, config-driven landing page, agent authoring
 * scaffold (CLAUDE.md/AGENTS.md) — and none of the classic-template cruft.
 */

export interface ScaffoldOptions {
  /** Target directory for the new site. */
  directory: string;
  /** Site display name. Defaults to the directory basename. */
  siteName?: string;
  /** Site tagline, shown in the landing hero. */
  tagline?: string;
  /** Primary brand color (hex), compiled by @pokedocs/theme (F1.4). */
  brandColor?: string;
  /** Logo file (.svg/.png) copied into the scaffold; omitted → a brand-colored default is generated. */
  logo?: string;
  /** Deploy target scaffolded via `pokedocs deploy init` (S1.7.1/S1.7.2). */
  deploy?: 'github-pages' | 'docker' | 'none';
  /** GitHub owner (user or org) — required when deploy is 'github-pages'. */
  githubOwner?: string;
  /** GitHub repository name — defaults to the directory basename. */
  githubRepo?: string;
  /** Accept all defaults without prompting (S1.1.3). */
  yes?: boolean;
}

export {
  SCAFFOLD_DEFAULTS,
  type ScaffoldResult,
  scaffold,
} from './scaffold.js';
