/**
 * create-pokedocs — the scaffolder (PRD F1.1).
 *
 * `npx create-pokedocs my-docs` generates a docs-only site: docs at the root
 * path, autogenerated sidebar, config-driven landing page, agent authoring
 * scaffold (CLAUDE.md/AGENTS.md) — and none of the classic-template cruft.
 */

export interface ScaffoldOptions {
  /** Target directory for the new site. */
  directory: string;
  /** Site display name. */
  siteName?: string;
  /** Primary brand color (hex), compiled by @pokedocs/theme (F1.4). */
  brandColor?: string;
  /** Logo file to copy into the scaffold. */
  logo?: string;
  /** Deploy target scaffolded via `pokedocs deploy init` (S1.7.1/S1.7.2). */
  deploy?: 'github-pages' | 'docker' | 'none';
  /** Accept all defaults without prompting (S1.1.3). */
  yes?: boolean;
}

/**
 * Scaffold a new PokeDocs site. Implementation lands in M1 (S1.1.1–S1.1.3);
 * the skeleton pins the public shape.
 */
export async function scaffold(_options: ScaffoldOptions): Promise<never> {
  throw new Error(
    'create-pokedocs is not implemented yet — tracked by S1.1.1 (github.com/wbaxterh/pokedocs/issues).',
  );
}
